convert_task:
  description: >
    Convert the provided {email_file} in .eml format to an HTML file.
  expected_output: >
    An HTML file extracted from the provided {email_file}.
  agent: data_scientist

html_parse_task:
  description: >
    Parse the `out\email.html` html file and extract all the web links from it.
  expected_output: >
    CSV file with all the links extracted from the provided html.
  agent: data_scientist

correlate_task:
  description: >
    Correlate the links from the provided html with the clicks from {clicks_file}
  expected_output: >
    A list with the links from the provided html and the number of clicks they received
  agent: data_scientist

heatmap_task:
  description: >
    Generate a heatmap for the clicked links on the provided html
  expected_output: >
    A heatmap with the clicked links from the provided html drawn over html content
  agent: data_scientist
